CREATE TABLE Batches (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ProductionDate DATETIME NOT NULL,
    ExpirationDate DATETIME NOT NULL,
    Quantity INT NOT NULL
);

CREATE TABLE Products (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BatchId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Category NVARCHAR(100) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (BatchId) REFERENCES Batches(Id)
);

CREATE TABLE Orders (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    OrderDate DATETIME NOT NULL,
    CustomerName NVARCHAR(100) NOT NULL
);

CREATE TABLE OrderProducts (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    OrderId UNIQUEIDENTIFIER NOT NULL,
    ProductId UNIQUEIDENTIFIER NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES Orders(Id),
    FOREIGN KEY (ProductId) REFERENCES Products(Id)
);
